name: Sync Fork

on:
  schedule:
    # This runs at 1:00 UTC every day
    - cron: '0 1 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
      
      - name: Sync Main Branch
        run: |
          # Add upstream remote
          git remote add upstream https://github.com/UberGuidoZ/Flipper.git
          
          # Fetch all branches from upstream
          git fetch upstream
          
          # Explicitly check out and merge the main branch
          git checkout main
          git merge upstream/main
          git push origin main
      
      - name: Sync Device Branch
        run: |
          # Explicitly check out the device branch
          git checkout device
          
          # Merge upstream main into device branch
          git merge upstream/main
          
          # Push the updated device branch
          git push origin device
